name: agora_chat_uikit
description: A set of ui components adapted to the chat sdk can quickly build a chat page
  and chat through the chat sdk by invoking the ui components.
version: 1.1.0
homepage: https://www.agora.io/

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  image_picker: ^1.0.4
  file_picker: ^8.1.4
  record: ^5.2.0
  audioplayers: ^6.1.0
  agora_chat_sdk: ^1.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ease.em_chat_uikit
        pluginClass: FlutterChatUikitPlugin
      ios:
        pluginClass: FlutterChatUikitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - images/
 

